### ISSUE TITLE
how is it possible to tag images?

### ISSUE THREAD

**Issue by ConYel** [Polpetta/packer-plugin-podman#54]
I saw that there is a function `TagImage` but when I try to use it on the `post-processor` I get this:
```
Error: Unknown post-processor type "TagImage"

  on container-debian.pkr.hcl line 27:
  (source code not available)

The post-processor TagImage is unknown by Packer, and is likely part of a plugin
that is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=TagImage
```

**Comment by gardar** [comment]
The plugin only contains a builder and there is no post-processor in the plugin (as you can see from the missing post-processor directory).
But it shouldn't be too hard to add the post-processors from the docker driver.
But in the meantime you'd have to use a shell post-processor, or perhaps you can use the docker post processor. I'm myself using the shell post processor for pushing the images to a registry.

**Comment by gardar** [comment]
You should be able to use the ` ${build.ImageSha256}` variable for that.

As an example here's how you can export the image with a post processor after you commit it in packer. (I usually use commit rather than export in packer as it keeps the original layers.)

```
post-processor "shell-local" {
    inline = [
      "podman save --format oci-archive -o ${var.OUTPUT_TAR_PATH} ${build.ImageSha256}"
    ]
  }
```
